version: '3.0'

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - nesjs-network
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/postgresql.conf:/etc/postgresql/postgresql.conf
    logging:
      driver: none
    ports:
      - 5432:5432

  backend:
    depends_on:
      - db
    container_name: nestjs_api_dev
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    env_file:
      - ./server/.env.development
    ports:
      - 8080:8080
    networks:
      - nesjs-network

    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  client:
    depends_on:
      - backend
    build:
      context: ./client
      dockerfile: ./Dockerfile.dev
    restart: always

    env_file:
      - ./client/.env.development

    container_name: react_client_dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app/
      - /usr/src/app/node_modules



networks:
  nesjs-network: