version: '3.0'

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - nesjs-network
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/postgresql.conf:/etc/postgresql/postgresql.conf
    logging:
      driver: none
    ports:
      - 5432:5432

  backend:
    depends_on:
      - db
    container_name: nestjs_api_prod
    build:
      context: ./server
      dockerfile: ./Dockerfile.prod
      target: production
    env_file:
      - ./server/.env.production
    command: npm run start:prod
    ports:
      - 8080:8080
    networks:
      - nesjs-network
    restart: always

  client:
    depends_on:
      - backend
    build:
      context: ./client
      dockerfile: ./Dockerfile.prod
    restart: always

    env_file:
      - ./client/.env.production

    container_name: react_client_prod
    ports:
      - 3000:3000



networks:
  nesjs-network: